extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_ground_lights;
extern Lights1 bob_dl_dirt_lights;
extern u8 bob_dl_wf_textures_05800_rgba16_ci8[];
extern u8 bob_dl_wf_textures_05800_rgba16_ci8_pal_rgba16[];
extern u8 bob_dl_wf_textures_04800_rgba16_ci8[];
extern u8 bob_dl_wf_textures_04800_rgba16_ci8_pal_rgba16[];
extern Vtx bob_dl_Death_Plane_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_Death_Plane_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Island_1_mesh_layer_1_vtx_0[332];
extern Gfx bob_dl_Island_1_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Island_1_mesh_layer_1_vtx_1[180];
extern Gfx bob_dl_Island_1_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_f3d_material[];
extern Gfx mat_bob_dl_ground[];
extern Gfx mat_revert_bob_dl_ground[];
extern Gfx mat_bob_dl_dirt[];
extern Gfx mat_revert_bob_dl_dirt[];
extern Gfx bob_dl_Death_Plane_mesh_layer_5[];
extern Gfx bob_dl_Island_1_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
